FROM v2fly/v2fly-core:v5.30.0

COPY conf/v2ray.json.template /etc/v2ray/template.json
COPY scripts/v2ray-gen-config.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/v2ray-gen-config.sh

ENTRYPOINT ["/usr/local/bin/v2ray-gen-config.sh"]